Link GCP project using gcloud cli
doitintl/help pull request #160
Opened 2022-07-20 14:27 UTC by azure562

- Add a new section to use gcloud for project transfer
- Update screenshots

See CMP-4987

2022-07-20 14:42 UTC, norosa requested changes
Instead of blanking out areas of the screen, can we please use fake data of some sort? I typically edit it directly in my browser before taking the screenshot.

I think the banked-out areas are distracting, and conversely, the fake data, if chosen correctly, should give a good indication of what _type_ of values they should be seeing.

2022-07-24 11:56 UTC, norosa commented
Asked @yuvaldrori for a review. If he approves, I will merge with the screenshots as is. We can discuss our screenshots style guide separately. Since the UI has changed so much since many of our screenshots were generated, and given that we're dropping the pre-processed drop shadow, we are due for a whole-site refresh soon.

2022-07-24 11:58 UTC, norosa approved these changes
Dismissed my previous review (see previous comment). Here's the required approval from @DocOps. :)

2022-07-24 12:01 UTC, norosa commented
Squashed changes and resolved conflicts with `main`. I will mark this PR for auto-merge once we have a second approval from @yuvaldrori.

2022-07-24 15:17 UTC, norosa commented
Pushed some fixups. The tests should be good to go now.

2022-07-24 19:15 UTC, norosa commented
Preview URL here: https://deploy-preview-160--doitintl-help.netlify.app/

2022-07-25 08:44 UTC, norosa commented
The specific changes can be previewed on this page: https://deploy-preview-160--doitintl-help.netlify.app/docs/google-cloud/transfer-google-cloud-projects/transfer-manually

2022-07-25 12:25 UTC, kesor approved these changes
Two small suggestions, one left on the text file, the second suggestion -

The screenshots for Google Console originally had "cmp-playgrounds.com" as the customer's organization. The new screenshots show "doit-intl.com" at places. Not major issue, but would be nice to not show "doit-intl.com" as it might lead to confusion.

Other than these, looks good.

2022-07-25 12:25 UTC, kesor commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> +   gcloud projects list --format="value(project_id)" | xargs -I {} echo gcloud beta billing projects link {} --billing-account billing_account
Should be more obvious here that the word `billing_account` at the end of this line is the DoiT provided number, like in line 67 `0X0X0X-0X0X0X-0X0X0X`, but each customer might receive a unique one from DoiT.

2022-07-25 12:25 UTC, kesor commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> +   - `echo`: Displays a line of text. Dry run mode.
Maybe note here that `billing_account` piece at the end of the line is the number of the billing account provided by DoiT.

2022-07-25 12:36 UTC, norosa commented
I have tidied up the shell code a little to make it more readable, but more importantly, by formatting the commands as I have done, we can use the Docsaurus feature that lets us highlight the (very important) line with the `echo` statement used to determine if the command will be a dry-run or not.

As a bonus, I have added syntax highlighting for shell code.

It seems we have a conflict somewhere in our Docusaurus vs Prism CSS variables, the latter being used for code highlighting. The result is that the highlighted lines were far too dark for our current theme. So, along with my changes, I have added a small CSS root variables fix, using the same color value as used on the main Docusaurus website.

2022-07-25 12:37 UTC, norosa commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> +   gcloud projects list --format="value(project_id)" | xargs -I {} echo gcloud beta billing projects link {} --billing-account billing_account
Good shout. Fixed.

2022-07-25 12:41 UTC, norosa commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> +   - `echo`: Displays a line of text. Dry run mode.
Fixed!

2022-07-25 13:26 UTC, norosa commented
I have completely rewritten the `gcloud` section:

- Rephrased some parts for clarity
- Separated the instructions to replace variables into their own paragraphs
- Added a call out for the highlighted line with the `echo` command
- Reformatted the list of command parts as a definition list
- Pulled some information out into admonitions

2022-07-25 13:31 UTC, norosa commented
@kesor has reviewed my rewrite of the `gcloud` section and is happy with it. I have his approval to merge.

2022-07-25 13:31 UTC, merged

2022-07-25 13:37 UTC, norosa commented
> The screenshots for Google Console originally had "[cmp-playgrounds](https://doitintl.atlassian.net/browse/CMP-playgrounds).com" as the customer's organization. The new screenshots show "doit-intl.com" at places. Not major issue, but would be nice to not show "doit-intl.com" as it might lead to confusion.

Good point. We are going to do a screenshot refresh soon, and that will solve this issue. Unfortunately, Qing has not been able to get a playground account as of yet.