AWS cost allocation tags
doitintl/help pull request #189
Opened 2022-08-11 13:24 UTC by azure562

- Adjust the ordering of the lists of "Supported AWS cost allocation tags"
- Add "Reactivate custom cost allocation tags"
- Add "Limitations"
- Other minor editorial changes

See CMP-5199.

2022-08-16 11:54 UTC, kesor approved these changes
cleanup looks great

2022-08-18 12:55 UTC, norosa approved these changes
Looks good. Sorry my Prettier bug is complicating your work. I'll see if I can get to it during a small DocOps maintenance run tomorrow.

2022-08-18 12:55 UTC, norosa commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> +<<<<<<< HEAD
This is caused by https://github.com/doitintl/help/pull/192

I would comment upstaging this file from the PR and rebasing for now until the bug is fixed.

2022-08-18 12:57 UTC, norosa requested changes

2022-08-18 12:57 UTC, norosa commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> ----
Looks like your latest push deletes the file instead of unstaging it from the commit. I figure that's a mistake. Gimme a shout if you want me to assist and clean up the mess that my bug is causing on your PR,

2022-08-18 13:01 UTC, azure562 commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> ----
yes, you're right. I tried to unstage it in my local environment but it didn't work. Please help to fix it if it's not too difficult from your side.

2022-08-18 13:06 UTC, norosa commented on website/docs/google-cloud/transfer-google-cloud-projects/transfer-manually.mdx
> ----
I'm on it ⛑️

2022-08-18 13:14 UTC, norosa commented on .brokdb
> +>>>>>>> 9d46b0c... wrap up
I'll fix this too while I'm at it. I think we need to figure out a better way to cache these results so that they don't produce so many conflicts.

For context, we check this file because a fresh `brok` check takes a very long time to complete. Having the cache file checked in means that we get to share to results of running `brok` between maintainers (and the CICD) system, which reduces the time `make check` takes to run.

Making `make check` run as quickly as possible has been my priority. It's the same reason we cache the results from optipng. If we didn't, then you'd have to wait for optipng to check every image in the repository every time you ran `make check`. Instead, what we do is once we have verified that an image has been compressed, we write an md5sum to a file and tar.gz that up at the end so it can be committed. Every time you run `make check` is opens that file and scans the images looking for md5sums that don't match (i.e., new or changed) and only run optipng on those files.

Any input here from anyone on @doitintl/docops regarding how to improve the way we cache this data is welcome. I'm sort of making it up as I go along based on what I've seen elsewhere, but I may be missing something obvious that would reduce the issues it causes when rebasing against a `main` branch with more up-to-date cache,

2022-08-18 13:55 UTC, norosa commented
@azure562 Phew. That was quite a challenge. I feel dizzy (literally). But I think I got there in the end. Sorry for all the mess these checks produced.

Something I added in one of my commits was that I sorted the `.brokdb` file. I figure that having a deterministic order will help prevent future issues like this.

I have updated the `brok` CI script to do the same: https://github.com/doitintl/help/pull/199 (added you as a reviewer)

If we merge my CI enhancement PR first (which performs and commits the first sorted version of the file) and then rebase this again, we should see that the changes to the `.brokdb` file are minimal.

2022-08-18 15:44 UTC, norosa commented
Okay, so to make things easier, I made it so that `make brok` automatically fixes any merge conflicts. I cherry-picked that change into https://github.com/doitintl/help/pull/200, and I have rebased this branch onto that one because #200 should be merged first.

Once it's merged, we can rebase this onto main.

2022-08-18 15:46 UTC, norosa commented
Once #200 is approved and merged (I added you as a reviewer) this branch can be rebased onto main with all my changes marked as fixups, and then it should be good to go.

Once again, as this is my mess, I'd be happy to do that for you and leave you with a pristine PR that is ready for merging.

2022-08-19 09:01 UTC, azure562 commented
> #200

Thanks @norosa ! I'll rebase this one once [the other PR](https://github.com/doitintl/help/pull/200) is merged!

2022-08-19 13:47 UTC, norosa approved these changes

2022-08-19 13:54 UTC, merged