Add Pulse dashboard page
doitintl/help pull request #194
Opened 2022-08-16 09:07 UTC by azure562

- Add a new page for the Pulse dashboard.

See CMP-5359

2022-08-16 09:09 UTC, chaim0m commented on website/docs/dashboards/pulse.mdx
> +To avoid obscuring the high-level view of cloud spending trends, we exclude negative costs generated by _Credit_ or _Credit Adjustment_ items from the preset report widgets. You can [Open full report
```maybe?
To avoid obscuring the high-level view of cloud spending trends, we exclude negative costs generated by _Credit_ or _Credit Adjustment_ items from the preset report widgets. You can [Open full report](add-reports-to-dashboards.mdx#open-full-report) and change it in the report configurations if you would like to.
```

2022-08-16 09:11 UTC, chaim0m commented on website/docs/dashboards/pulse.mdx
> +The total cost in CloudHealth shouldn't be compared with that in the CMP in a live view. There are different data delays caused by contracts or discounts.
is the difference in discount only because of a delay?

2022-08-16 09:11 UTC, chaim0m commented on website/docs/dashboards/pulse.mdx
> +The reports always run against the current data, whereas the widgets are refreshed periodically. So there could be a delay between the them.
```suggestion
The reports always run against the current data, whereas the widgets are refreshed periodically. So there could be a delay between them.
```

2022-08-16 12:57 UTC, azure562 commented on website/docs/dashboards/pulse.mdx
> +To avoid obscuring the high-level view of cloud spending trends, we exclude negative costs generated by _Credit_ or _Credit Adjustment_ items from the preset report widgets. You can [Open full report
Added "or [customize the preset report](../cloud-analytics/reports/create-report.mdx#clonecustomize-from-the-report-page) to create your own one."

2022-08-16 12:58 UTC, azure562 commented on website/docs/dashboards/pulse.mdx
> +The total cost in CloudHealth shouldn't be compared with that in the CMP in a live view. There are different data delays caused by contracts or discounts.
it's also because "certain discounts and promotional credits in the CMP are not included in CloudHealth"

2022-08-18 12:50 UTC, norosa requested changes
I have reviewed it from a purely DocOps perspective. Will leave the content review to the SME(s). The screenshots look good. Changes look good. Documentation formatting looks good.

I'm requesting changes because of this line:

```
sidebar_position: 6
```

It's a real PITA, but I have been trying to keep the `sidebar_position` numbers consistent whenever I make a change.

In this case the following files would need to be changed:

- `rightsizing-for-google-cloud.mdx` (bump to 7)
- `bigquery-lens.mdx` (bump to 8)
- `aws-lens.mdx` (bump to 9)

I have added a ticket for potentially upgrading our CI system to catch this (and possibly fix it for you automatically): https://doitintl.atlassian.net/browse/CMP-5549

2022-08-18 12:59 UTC, azure562 commented
> I have reviewed it from a purely DocOps perspective. Will leave the content review to the SME(s). The screenshots look good. Changes look good. Documentation formatting looks good.
> 
> I'm requesting changes because of this line:
> 
> ```
> sidebar_position: 6
> ```
> 
> It's a real PITA, but I have been trying to keep the `sidebar_position` numbers consistent whenever I make a change.
> 
> In this case the following files would need to be changed:
> 
> * `rightsizing-for-google-cloud.mdx` (bump to 7)
> * `bigquery-lens.mdx` (bump to 8)
> * `aws-lens.mdx` (bump to 9)
> 
> I have added a ticket for potentially upgrading our CI system to catch this (and possibly fix it for you automatically): https://doitintl.atlassian.net/browse/CMP-5549

Sorry but I prefer to keep this as is. I've checked the sidebar_position number when adding it. There are upcoming changes in this section, including the new GKE Lens page. I would like to change them all in one PR later. Another consideration is I'm thinking to adjust the order in this section

2022-08-18 13:04 UTC, norosa commented
@azure562 fair enough. Seems like a reasonable approach. I have rescinded my change request.

2022-08-23 08:12 UTC, Dror88 commented on website/docs/dashboards/pulse.mdx
> +The summary cards are updated every 12 hours.
"and widgets"

2022-08-23 08:18 UTC, Dror88 approved these changes

2022-08-23 08:27 UTC, caparroz approved these changes
Reviewed and commented offline. Changes now applied, approving.

2022-08-23 08:44 UTC, norosa approved these changes

2022-08-23 08:46 UTC, merged